# Generated by Django 3.2.19 on 2024-10-11 12:54

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(verbose_name='Итоговая сумма')),
                ('status', django_enum.fields.EnumCharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=11)),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_time_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('status', django_enum.fields.EnumCharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=6)),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Картинка')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('price', models.FloatField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Paid', 'Unpaid'])), name='orders_Payment_status_PaymentStatus'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Confirmed', 'Unconfirmed'])), name='orders_Order_status_OrderStatus'),
        ),
    ]
