# Generated by Django 4.2.16 on 2024-10-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
